c ----------------------------------------------------------------------
c  MAIN PROGRAM - generated by the Rappture Builder
c ----------------------------------------------------------------------
      program main
        IMPLICIT NONE

c       stuff needed for Rappture:
        integer rp_lib, rp_units_convert_dbl
        integer io, ok
        character*255 inFile, strVal
 

      integer nletters
      parameter ( nletters = 26 )

      integer wordb / 0 /
      integer nwords / 0 /
      integer count(nletters), i, c
      character*100 line

c       for input.string(value1)
        character*255 value1


c       open the XML file containing the run parameters
        call getarg(1,inFile)
        io = rp_lib(inFile)
        if (io .eq. 0) then
            write(6,*) "FAILED loading Rappture data from ",inFile
            stop
        endif

c       ----------------------------------------------------------
c       Get input values from Rappture
c       ----------------------------------------------------------

c       get input value for input.string(value1)
        call rp_lib_get(io,
     +    "input.string(value1).current", value1)


c       ----------------------------------------------------------
c          Add your code here for the main body of your program
c       ----------------------------------------------------------
c     zero out all counts
      do 10 i=1,nletters
        count(i) = 0
 10   continue
      
      line = value1
      do 20 i=1,len(TRIM(line))
        if ((line(i:i).eq.' ').or.(line(i:i).eq.'\t').or.
     +      (line(i:i).eq.'\n')) then
          wordb = 0
        else if ((line(i:i).ge.'a').and.(line(i:i).le.'z')
     +      .or. (line(i:i).ge.'A').and.(line(i:i).le.'Z')) then
            if (wordb.ne.1) then
                nwords = nwords + 1
                wordb = 1
            endif
        endif

        if (line(i:i).ge.'A'.and.line(i:i).le.'Z') then
            c = ichar(line(i:i)) - ichar('A') + 1
        else
            c = ichar(line(i:i)) - ichar('a') + 1
        endif
        if (c.ge.1 .and. c.le.nletters) then
            count(c) = count(c) + 1
        endif
 20   continue

c       spit out progress messages as you go along...
        call rp_utils_progress (0, "Starting...")
        call rp_utils_progress (5, "Loading data...")
        call rp_utils_progress (50, "Half-way there")
        call rp_utils_progress (100, "Done")

c       ----------------------------------------------------------
c       Save output values back to Rappture
c       ----------------------------------------------------------

c       save output value for output.histogram(value6)
c       this shows just one point -- modify as needed
c       (x,h,w) = x-coord, height of bar, and width of bar (optional)
        do 30 i=1,nletters
           if (count(i).gt.0) then
              write(strVal,'(E20.12,E20.12,E20.12,A)') x, h, w, char(10)
              call rp_lib_put_str(io,
     +    "output.histogram(value6).component.xy",strVal,1)
           endif
 30     continue


        call rp_result(io)
      end program main
